version: 2
jobs:
  test:
    docker:
      - image: quay.io/quintype/docker-base:circleci-node8-npm6
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  default:
    jobs:
      - test
